### ISSUE TITLE
 org.tpolecat#tut-core_2.11;0.3.0: not found

### ISSUE THREAD

**Issue by gbougeard** [tpolecat/tut#39]
I think 2.11 binaries are not available on bintray.

**Comment by tpolecat** [comment]
This works if you are running tut ...

```
[info] downloading http://dl.bintray.com/tpolecat/maven/org/tpolecat/tut-core_2.11/0.3.0/tut-core_2.11-0.3.0.jar ...
[info] 	[SUCCESSFUL ] org.tpolecat#tut-core_2.11;0.3.0!tut-core_2.11.jar (944ms)
```

So my guess is that you're using a library that has pulled in the tut runtime as a dependency, which is harmless but is a bug in the way the plugin is set up. This should be fixed in the next version. For now you need to add the resolver:

```scala
resolvers += "tpolecat" at "http://dl.bintray.com/tpolecat/maven"
```

Let me know if this fixes your problem.

**Comment by gbougeard** [comment]
Yep, I solved it. Thx
